### ISSUE TITLE
Bad gamedata

### ISSUE THREAD

**Issue by GamerXCZ** [vanz666/NoLobbyReservation#1]
`[SM] Exception reported: Failed to load CBaseServer::IsExclusiveToLobbyConnections signature from gamedata`

**Comment by vanz666** [comment]
It looks like a conflict with a third-party plugin that hooks this function.

**Comment by GamerXCZ** [comment]
I not using another plugin for this fuction.

**Comment by vanz666** [comment]
What type of OS and SM version are you using? I can edit gamedata to fix this.

**Comment by GamerXCZ** [comment]
```
SourceMod Version Information:
SourceMod Version: 1.10.0.6492
SourcePawn Engine: 1.10.0.6492, jit-x86 (build 1.10.0.6492)
SourcePawn API: v1 = 5, v2 = 12
Compiled on: Jul 24 2020 20:07:18
Built from: https://github.com/alliedmodders/sourcemod/commit/250886f
Build ID: 6492:250886f
```

Linux

**Comment by vanz666** [comment]
Try this [nolobbyreservation.games.txt](https://github.com/vanz666/NoLobbyReservation/files/5096979/nolobbyreservation.games.txt)

**Comment by GamerXCZ** [comment]
Works. Thanks

**Comment by GamerXCZ** [comment]
Now I run both plugins noVAC and this and when player try connect with VAC throw this error:
`RejectConnection: _ip:port_ - #Valve_Reject_Reserved_For_Lobby`

**Comment by vanz666** [comment]
Did you restart the server before doing this?

**Comment by GamerXCZ** [comment]
Nobody Can't connect

And no i just use sm load. I will try with restart.

**Comment by vanz666** [comment]
You must restart the server after installing this plugin.

**Comment by GamerXCZ** [comment]
Works thanks for help.
