### ISSUE TITLE
Gamedata broke with latest CSGO update

### ISSUE THREAD

**Issue by crashzk** [vanz666/NoLobbyReservation#2]
This plugin crashes the server after the last csgo update

**Comment by crashzk** [comment]
I also noticed that after the update the players are being kicked by sv_pure, even though it is disabled.

![image](https://user-images.githubusercontent.com/32937653/197395623-bea7d079-59cc-4bf7-8ba4-dbdfb1dc89c8.png)

I completely removed NoLobbyReservation and ended the kicks by sv_pure.

@vanz666

**Comment by neoneeeee** [comment]
интересно как ты нашел эти сигнатуры  и сделал плагин, не плохо однако!
